### ISSUE TITLE
ubuntu 20.04 error when use python3 -m pip wheel . --verbose

### ISSUE THREAD

**Issue by jaffe-fly** [opencv/opencv-python#471]
### Expected behaviour
I have set ```export ENABLE_CONTRIB=1```  and when use ```python3 -m pip install numpy==1.17.3```, numpy can successfully installed,But ```python3 -m pip wheel . --verbose```,still error in numpy
how to solve this

### Actual behaviour
```
creating '/tmp/pip-modern-metadata-sl825rcp/opencv_contrib_python.dist-info'
    adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
    adding license file "LICENSE-3RD-PARTY.txt" (matched pattern "LICEN[CS]E*")
    /tmp/pip-build-env-_5y1_ljm/overlay/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
      warnings.warn(
    Preparing wheel metadata ... done
  Source in /tmp/pip-req-build-rh2gc9fj has version 4.5.1.48, which satisfies requirement opencv-contrib-python==4.5.1.48 from file:///tmp/opencv-python
  Removed opencv-contrib-python==4.5.1.48 from file:///tmp/opencv-python from build tracker '/tmp/pip-req-tracker-p8oifmas'
WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
0 location(s) to search for versions of numpy:
Given no hashes to check 0 links for project 'numpy': discarding no candidates
ERROR: Could not find a version that satisfies the requirement numpy>=1.17.3 (from opencv-contrib-python==4.5.1.48) (from versions: none)
Cleaning up...
  Removing source in /tmp/pip-req-build-rh2gc9fj
Removed build tracker: '/tmp/pip-req-tracker-p8oifmas'
ERROR: No matching distribution found for numpy>=1.17.3 (from opencv-contrib-python==4.5.1.48)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/wheel.py", line 161, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for numpy>=1.17.3 (from opencv-contrib-python==4.5.1.48)
```
 - [ √] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
The issues is not related to this repository. Your `pip` is not configured correctly:

> WARNING: The repository located at **mirrors.cloud.aliyuncs.com** is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
> **0 location(s) to search for versions of numpy:
> Given no hashes to check 0 links for project 'numpy': discarding no candidates**

Please check your environment configuration.
