### ISSUE TITLE
TypeError: VideoCapture() takes no arguments

### ISSUE THREAD

**Issue by savadkv01** [opencv/opencv-python#518]
This is the code which iam tryng in PyCharm

import cv2
import time

cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    cv2.imshow("Image", img)
    cv2.waitKey(1)

Iam getting below error

"C:\Users\Support ACTA\AppData\Local\Programs\Python\Python37\python.exe" "E:/Project/Python/advanced computer vision/Face Detection/FaceDetectionMin.py"
Traceback (most recent call last):
  File "E:/Project/Python/advanced computer vision/Face Detection/FaceDetectionMin.py", line 4, in <module>
    cap = cv2.VideoCapture(0)
TypeError: VideoCapture() takes no arguments

If I use the the video path also, same error iam getting

**Comment by asmorkalov** [comment]
Please provide `cv2.getBuildInformation()` call output.

**Comment by savadkv01** [comment]
>>> import cv2
>>> cv2.getBuildInformation()
'\nGeneral configuration for OpenCV 4.5.3 =====================================\n  Version control:               4.5.3\n\n  Extra modules:\n    Location (extra):            C:/Users/runneradmin/AppData/Local/Temp/pip-req-build-_xlv4eex/opencv_contrib/modules\n    Version control (extra):     4.5.3\n\n  Platform:\n    Timestamp:                   2021-07-09T11:26:41Z\n    Host:                        Windows 10.0.17763 AMD64\n    CMake:                       3.20.5\n    CMake generator:             Visual Studio 14 2015 Win64\n    CMake build tool:            MSBuild.exe\n    MSVC:                        1900\n    Configuration:               Debug Release\n\n  CPU/HW features:\n    Baseline:                    SSE SSE2 SSE3\n      requested:                 SSE3\n    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2\n      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX\n      SSE4_1 (15 files):         + SSSE3 SSE4_1\n      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2\n      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX\n      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX\n      AVX2 (29 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2\n\n  C/C++:\n    Built as dynamic libs?:      NO\n    C++ standard:                11\n    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24245.0)\n    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MT /O2 /Ob2 /DNDEBUG \n    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MTd /Zi /Ob0 /Od /RTC1 \n    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe\n    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MT /O2 /Ob2 /DNDEBUG \n    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MTd /Zi /Ob0 /Od /RTC1 \n    Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib\n    Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib\n    ccache:                      NO\n    Precompiled headers:         YES\n    Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32\n    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv\n\n  OpenCV modules:\n    To be built:                 aruco barcode bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto\n    Disabled:                    freetype world\n    Disabled by dependency:      -\n    Unavailable:                 alphamat cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv hdf java julia matlab ovis python2 sfm ts viz\n    Applications:                -\n    Documentation:               NO\n    Non-free algorithms:         NO\n\n  Windows RT support:            NO\n\n  GUI: \n    Win32 UI:                    YES\n    VTK support:                 NO\n\n  Media I/O: \n    ZLib:                        build (ver 1.2.11)\n    JPEG:                        build-libjpeg-turbo (ver 2.1.0-62)\n    WEBP:                        build (ver encoder: 0x020f)\n    PNG:                         build (ver 1.6.37)\n    TIFF:                        build (ver 42 - 4.2.0)\n    JPEG 2000:                   build (ver 2.4.0)\n    OpenEXR:                     build (ver 2.3.0)\n    HDR:                         YES\n    SUNRASTER:                   YES\n    PXM:                         YES\n    PFM:                         YES\n\n  Video I/O:\n    DC1394:                      NO\n    FFMPEG:                      YES (prebuilt binaries)\n      avcodec:                   YES (58.134.100)\n      avformat:                  YES (58.76.100)\n      avutil:                    YES (56.70.100)\n      swscale:                   YES (5.9.100)\n      avresample:                YES (4.0.0)\n    GStreamer:                   NO\n    DirectShow:                  YES\n    Media Foundation:            YES\n      DXVA:                      YES\n\n  Parallel framework:            Concurrency\n\n  Trace:                         YES (with Intel ITT)\n\n  Other third-party libraries:\n    Intel IPP:                   2020.0.0 Gold [2020.0.0]\n           at:                   C:/Users/runneradmin/AppData/Local/Temp/pip-req-build-_xlv4eex/_skbuild/win-amd64-3.7/cmake-build/3rdparty/ippicv/ippicv_win/icv\n    Intel IPP IW:                sources (2020.0.0)\n              at:                C:/Users/runneradmin/AppData/Local/Temp/pip-req-build-_xlv4eex/_skbuild/win-amd64-3.7/cmake-build/3rdparty/ippicv/ippicv_win/iw\n    Lapack:                      NO\n    Eigen:                       NO\n    Custom HAL:                  NO\n    Protobuf:                    build (3.5.1)\n\n  OpenCL:                        YES (NVD3D11)\n    Include path:                C:/Users/runneradmin/AppData/Local/Temp/pip-req-build-_xlv4eex/opencv/3rdparty/include/opencl/1.2\n    Link libraries:              Dynamic load\n\n  Python 3:\n    Interpreter:                 C:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe (ver 3.7.9)\n    Libraries:                   C:/hostedtoolcache/windows/Python/3.7.9/x64/libs/python37.lib (ver 3.7.9)\n    numpy:                       C:/Users/RUNNER~1/AppData/Local/Temp/pip-build-env-fgp09wnn/overlay/Lib/site-packages/numpy/core/include (ver 1.14.5)\n    install path:                python\n\n  Python (for build):            C:/hostedtoolcache/windows/Python/2.7.18/x64/python.exe\n\n  Java:                          \n    ant:                         NO\n    JNI:                         C:/hostedtoolcache/windows/Java_Adopt_jdk/8.0.292-10/x64/include C:/hostedtoolcache/windows/Java_Adopt_jdk/8.0.292-10/x64/include/win32 C:/hostedtoolcache/windows/Java_Adopt_jdk/8.0.292-10/x64/include\n    Java wrappers:               NO\n    Java tests:                  NO\n\n  Install to:                    C:/Users/RUNNER~1/AppData/Local/Temp/pip-req-build-_xlv4eex/_skbuild/win-amd64-3.7/cmake-install\n-----------------------------------------------------------------\n\n'

**Comment by abhiTronix** [comment]
@savadkv01 This may be a problem with Pycharm, I guess you could also just silence the warning in the IDE, by adding a noinspection comment.
```python
# noinspection PyArgumentList
cap = cv2.VideoCapture(0)
```
More information here: https://stackoverflow.com/questions/39929166/cv2-python-videocapture0-unexpected-argument

**Comment by savadkv01** [comment]
Hi,
When I use python on command prompt also, same issue is getting.
![Screenshot_2](https://user-images.githubusercontent.com/64827558/127730565-e10fabaf-31fc-49f1-8362-c2780d568acc.jpg)

C:\Users\Support ACTA>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> print(cv2.__version__)
4.5.3
>>> cv2.VideoCapture(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: VideoCapture() takes no arguments
>>>

**Comment by asmorkalov** [comment]
Linux version works as expected:
```
~$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2 as cv
>>> qq = cv.VideoCapture(0)
>>> print(qq)
<VideoCapture 0x7f70094d7750>
```

I need some time to reproduce the same on Windows host and I'll come back.

**Comment by asmorkalov** [comment]
Windows works ok for me:
```
C:\Users\xperience>python -m pip install --upgrade opencv-python
Collecting opencv-python
  Downloading opencv_python-4.5.3.56-cp39-cp39-win_amd64.whl (34.9 MB)
     |████████████████████████████████| 34.9 MB 1.6 MB/s
Requirement already satisfied: numpy>=1.19.3 in c:\users\xperience\appdata\local\programs\python\python39\lib\site-packages (from opencv-python) (1.20.3)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.5.3.56
WARNING: You are using pip version 21.1.1; however, version 21.2.2 is available.
You should consider upgrading via the 'C:\Users\xperience\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

C:\Users\xperience>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print(cv.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cv' is not defined
>>> import cv2 as cv
>>> print(cv.__version__)
4.5.3
>>> cv.VideoCapture(0)
<VideoCapture 000002BBF4561A70>
>>>
```

**Comment by Enzo-Azevedo** [comment]
OpenCV 4.7.0.72 keeps the error. When I was checking, Class VideoCapture had "pass".
![image](https://user-images.githubusercontent.com/118974042/234395254-a26f184a-2b11-4841-beae-b1267ec176c0.png)

**Comment by Ibrahimshaikh1258** [comment]
I'm facing same problem try different options not solving the problem this comments useful.
@asmorkalov Thanks for the solved the problem.
