### ISSUE TITLE
Symbol not found: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by johnwilsin** [opencv/opencv-python#789]
opencv-python  version 4.7.0.68
python version 3.9.7

123456deMBP:python_selenium a123456$ python3 
Python 3.9.7 (default, Oct 13 2021, 06:43:37) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> 
>>> import cv2 as cv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/cv2/cv2.abi3.so, 2): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /usr/local/lib/python3.9/site-packages/cv2/.dylibs/libX11.6.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.9/site-packages/cv2/.dylibs/libX11.6.dylib

**Comment by asmorkalov** [comment]
OpenCV uses github actions for CI and releases. Github deprecated mac 10.x and does not support it. So all builds are switched to Mac OS 11.
Related issue: https://github.com/actions/runner-images/issues/5583

**Comment by asmorkalov** [comment]
Related GHA issue: https://github.com/actions/setup-python/issues/26
